from config import language

if language == 'cn':
    codes = {
        '0': '操作成功',
        '1': '操作全部失败',
        '2': '批量操作部分成功',
        '50000': 'body不能为空',
        '50001': '服务暂时不可用，请稍后重试',
        '50002': '非法的json数据',
        '50004': '接口请求超时（不代表请求成功或者失败，请检查请求结果）',
        '50005': '接口已下线或无法使用',
        '50006': '无效的Content_Type，请使用"application/json"格式',
        '50007': '用户被冻结',
        '50008': '用户不存在',
        '50009': '用户处于爆仓冻结',
        '50010': '用户ID为空',
        '50011': '用户请求频率过快，超过该接口允许的限额',
        '50012': '用户状态无效',
        '50013': '当前系统繁忙，请稍后重试',
        '50014': '必填参数{0}不能为空',
        '50015': '参数{0}和{1}不能同时为空',
        '50016': '参数{0}和{1}不匹配',
        '50017': '当前仓位处于ADL冻结中，无法进行相关操作',
        '50018': '{0}币种处于ADL冻结中，无法进行相关操作',
        '50019': '当前账户处于ADL冻结中，无法进行相关操作',
        '50020': '当前仓位处于强平冻结中，无法进行相关操作',
        '50021': '{0}币种处于强平冻结中，无法进行相关操作',
        '50022': '当前账户处于强平冻结中，无法进行相关操作',
        '50023': '资金费冻结，无法进行相关操作',
        '50024': '参数{0}和{1}不能同时存在',
        '50025': '参数{0}传值个数超过最大限制{1}',
        '50026': '系统错误',
        '50027': '当前账户已被限制交易',
        '50028': '账户异常无法下单',
        '50029': '你的账户已经触发风控体系，禁止该标的{0}交易，请联系客服进行处理',
        '50030': '用户没有使用此API接口的权限',
        '50031': '设置币种数量不能大于100个',
        '50032': '您的账户已设置禁止该币种交易，请确认后重试',
        '50033': '您的账户已设置禁止该业务线交易，请确认后重试',
        '50100': 'Api已被冻结，请联系客服处理',
        '50101': 'APIKey与当前环境不匹配',
        '50102': '请求时间戳过期',
        '50103': '请求头"OK_ACCESS_KEY"不能为空',
        '50104': '请求头"OK_ACCESS_PASSPHRASE"不能为空',
        '50105': '请求头"OK_ACCESS_PASSPHRASE"错误',
        '50106': '请求头"OK_ACCESS_SIGN"不能为空',
        '50107': '请求头"OK_ACCESS_TIMESTAMP"不能为空',
        '50108': '券商ID不存在',
        '50109': '券商域名不存在',
        '50110': '无效的ip',
        '50111': '无效的OK_ACCESS_KEY',
        '50112': '无效的OK_ACCESS_TIMESTAMP',
        '50113': '无效的签名',
        '50114': '无效的授权',
        '50115': '无效的请求类型',
        '51000': '{0}参数错误',
        '51001': '交易产品ID不存在',
        '51002': '交易产品ID不匹配指数',
        '51003': 'ordId或clOrdId至少填一个',
        '51004': '委托数量超过用户当前档位',
        '51005': '委托数量大于单笔上限',
        '51006': '委托价格不在限价范围内',
        '51007': '委托失败，委托数量不可小于1张（用户下单数量不足1张时）',
        '51008': '委托失败，账户可用余额不足',
        '51009': '下单功能被平台冻结',
        '51010': '当前账户模式不支持此操作',
        '51011': 'ordId重复',
        '51012': '币种不存在',
        '51014': '指数不存在',
        '51015': 'instId和instType不匹配',
        '51016': 'clOrdId重复',
        '51017': '杠杆委托交易借币超出限额',
        '51018': '期权交易账户不能有净空头持仓',
        '51019': '期权全仓不能有净多头持仓',
        '51020': '委托数量必须超过单笔下限',
        '51021': '合约待上线',
        '51022': '合约暂停中',
        '51023': '仓位不存在',
        '51024': '统一账户冻结',
        '51025': '委托笔数超限',
        '51026': '交易产品类型不匹配指数（instType和uly不匹配）',
        '51027': '合约已到期',
        '51028': '合约交割中',
        '51029': '合约结算中',
        '51030': '资金费结算中',
        '51031': '委托价格不在平仓限价范围内',
        '51041': 'PM账户仅支持买卖模式',
        '51044': '当前订单类型{0},{1}不支持设置止盈和止损',
        '51046': '止盈触发价格应该大于委托价格',
        '51047': '止损触发价格应该小于委托价格',
        '51048': '止盈触发价格应该小于委托价格',
        '51049': '止损触发价格应该大于委托价格',
        '51050': '止盈触发价格应该大于卖一价',
        '51051': '止损触发价格应该小于卖一价',
        '51052': '止盈触发价格应该小于买一价',
        '51053': '止损触发价格应该大于买一价',
        '51100': '币交易金额小于最小可交易金额',
        '51101': '超出单笔最大挂单张数',
        '51102': '超出合约最大挂单数量',
        '51103': '超出标的最大挂单数量',
        '51104': '超出标的最大挂单张数',
        '51105': '超出合约最大可开张数',
        '51106': '超出标的最大可开张数',
        '51107': '超出标的最大持仓张数',
        '51108': '持仓量超过市价全平最大限制',
        '51109': '订单深度中无买一卖一价',
        '51110': '集合竞价开始后方可下限价单',
        '51111': '批量下单时，超过最大单数{0}',
        '51112': '平仓张数大于该仓位的可平张数',
        '51113': '市价全平操作过于频繁',
        '51115': '市价全平前请先撤销所有平仓单',
        '51116': '委托价格或触发价格超过{0}美元',
        '51117': '平仓单挂单单数超过限制',
        '51118': '委托总数量需大于单笔上限',
        '51120': '下单数量不足{0}张',
        '51121': '下单张数应为一手张数的倍数',
        '51122': '委托价格小于最小值{0}',
        '51124': '价格发现期间您只可下限价单',
        '51125': '当前杠杆存在非只减仓挂单，请撤销所有非只减仓挂单后进行只减仓挂单',
        '51126': '当前杠杆存在只减仓挂单，请撤销所有只减仓挂单后进行非只减仓挂单',
        '51127': '仓位可用余额为0',
        '51128': '跨币种账户无法进行全仓杠杆交易',
        '51129': '持仓及买入订单价值已达到持仓限额，不允许继续买入',
        '51130': '逐仓杠杆保证金币种错误',
        '51131': '仓位可用余额不足',
        '51132': '仓位正资产小于最小交易单位',
        '51133': '跨币种全仓币币不支持只减仓功能',
        '51134': '平仓失败，请检查持仓和挂单',
        '51135': '您的平仓价格已触发限价，最高买入价格为{0}',
        '51136': '您的平仓价格已触发限价，最低卖出价格为{0}',
        '51137': '您的开仓价格已触发限价，最高买入价格为{0}',
        '51138': '您的开仓价格已触发限价，最低卖出价格为{0}',
        '51139': '交易账户下币币不支持只减仓功能',
        '51145': '逐仓自主划转保证金模式不支持提前挂单',
        '51147': '交易账户资产总价值需要大于5万美元来交易期权',
        '51148': '只减仓委托仅允许减少仓位数量，确保你的仓位不会增加',
        '51201': '市价委托单笔价值不能超过1,000,000USDT',
        '51202': '市价单下单数量超出最大值',
        '51203': '普通委托数量超出最大限制{0}',
        '51204': '限价委托单价格不能为空',
        '51205': '不支持只减仓操作',
        '51250': '策略委托价格不在正确范围内',
        '51251': '策略委托类型错误',
        '51252': '策略委托数量不在正确范围内',
        '51253': '冰山委托单笔均值超限',
        '51254': '冰山委托单笔均值错误',
        '51255': '冰山委托单笔委托超限',
        '51256': '冰山委托深度错误',
        '51257': '跟踪委托回调服务错误，回调幅度限制为{0}<x<={1}%',
        '51258': '跟踪委托失败，卖单激活价格需大于最新成交价格',
        '51259': '跟踪委托失败，买单激活价格需小于最新成交价格',
        '51260': '每个用户最多可同时持有{0}笔未成交的跟踪委托',
        '51261': '每个用户最多可同时持有{0}笔未成交的止盈止损',
        '51262': '每个用户最多可同时持有{0}笔未成交的冰山委托',
        '51263': '每个用户最多可同时持有{0}笔未成交的时间加权单',
        '51264': '时间加权单笔均值超限',
        '51265': '时间加权单笔上限错误',
        '51267': '时间加权扫单比例出错',
        '51268': '时间加权扫单范围出错',
        '51269': '时间加权委托间隔错误，应为{0}<=x<={1}',
        '51270': '时间加权委托深度限制为0<x<=1%',
        '51271': '时间加权委托失败，扫单比例应该为0<x<=100%',
        '51272': '时间加权委托失败，扫单范围应该为0<x<=1%',
        '51273': '时间加权委托总量应为大于0',
        '51274': '时间加权委托总数量需大于单笔上限',
        '51275': '止盈止损市价单笔委托数量不能超过最大限制',
        '51276': '止盈止损市价单不能指定价格',
        '51277': '止盈触发价格不能大于最新成交价',
        '51278': '止损触发价格不能小于最新成交价',
        '51279': '止盈触发价格不能小于最新成交价',
        '51280': '止损触发价格不能大于最新成交价',
        '51281': '计划委托不支持使用tgtCcy参数',
        '51282': '吃单价优于盘口的比例范围',
        '51283': '时间间隔的范围{0}s~{1}s',
        '51284': '单笔数量的范围{0}~{1}',
        '51285': '委托总量的范围{0}~{1}',
        '51286': '下单金额需大于等于{0}',
        '51287': '策略不支持此合约',
        '51288': '策略正在停止中，请勿重复点击',
        '51289': '策略配置不存在，请稍后再试',
        '51290': '策略引擎正在升级，请稍后重试',
        '51291': '策略不存在或已停止',
        '51292': '策略类型不存在',
        '51293': '策略不存在',
        '51294': '该策略暂不能创建，请稍后再试',
        '51295': 'PM账户不支持ordType为{0}的策略委托单',
        '51298': '交割、永续合约的买卖模式下，不支持计划委托',
        '51300': '止盈触发价格不能大于标记价格',
        '51302': '止损触发价格不能小于标记价格',
        '51303': '止盈触发价格不能小于标记价格',
        '51304': '止损触发价格不能大于标记价格',
        '51305': '止盈触发价格不能大于指数价格',
        '51306': '止损触发价格不能小于指数价格',
        '51307': '止盈触发价格不能小于指数价格',
        '51308': '止损触发价格不能大于指数价格',
        '51309': '集合竞价期间不能创建策略',
        '51310': '逐仓自主划转保证金模式不支持ordType为iceberg、twap的策略委托单',
        '51311': '移动止盈止损委托失败，回调幅度限制为{0}<x<={1}',
        '51312': '移动止盈止损委托失败，委托数量范围{0}<x<={1}',
        '51313': '逐仓自主划转模式不支持策略部分',
        '51037': '当前账户风险状态，仅支持降低账户风险方向的IOC订单',
        '51038': '当前风险模块下已经存在降低账户风险方向的IOC类型订单',
        '51039': 'PM账户下交割和永续的全仓不能调整杠杆倍数',
        '51040': '期权逐仓的买方不能调整保证金',
        '51400': '撤单失败，订单不存在',
        '51401': '撤单失败，订单已撤销',
        '51402': '撤单失败，订单已完成',
        '51403': '撤单失败，该委托类型无法进行撤单操作',
        '51404': '价格发现第二阶段您不可撤单',
        '51405': '撤单失败，您当前没有未成交的订单',
        '51406': '撤单数量超过最大允许单数{0}',
        '51407': 'ordIds和clOrdIds不能同时为空',
        '51408': '币对id或币对名称与订单信息不匹配',
        '51409': '币对id或币对名称不能同时为空',
        '51410': '撤单失败，订单已处于撤销中',
        '51500': '价格和数量不能同时为空',
        '51501': '修改订单超过最大允许单数{0}',
        '51502': '修改订单失败，用户保证金不足',
        '51503': '修改订单失败,订单不存在',
        '51506': '订单类型不支持改单',
        '51508': '集合竞价第一阶段和第二阶段不允许改单',
        '51509': '修改订单失败,订单已撤销',
        '51510': '修改订单失败,订单已完成',
        '51511': '修改订单失败,订单价格不满足PostOnly条件',
        '51512': '修改订单失败，PM账户下，批量改单不允许一批量请求中包含相同的订单',
        '51513': '改单校验失败，请稍后重试',
        '51600': '查询订单的状态不存在',
        '51601': '订单状态和订单id不能同时存在',
        '51602': '订单状态或订单id必须存在一个',
        '51603': '查询订单不存在',
        '52000': '没有最新行情信息',
        '54000': '暂不支持币币杠杆业务',
        '54001': '只有跨币种全仓账户才能设置自动借币',
        '55000': '交割后30分钟内不能转出',
        '58000': '获取母账户余额，{0}不支持',
        '58001': '交易密码错误',
        '58002': '请先开通余币宝服务',
        '58003': '余币宝不支持该币种',
        '58004': '账户冻结',
        '58005': '申购/赎回额度不可超过{0}',
        '58006': '币种{0}不支持当前操作',
        '58007': '资金接口服务异常，请稍后再试。',
        '58100': '行权或结算中，暂无法转入或转出',
        '58101': '划转冻结',
        '58102': '划转过于频繁，请降低划转频率',
        '58104': '您在法币区的交易异常，现已被限制划转功能，请您联系在线客服以解除限制',
        '58105': '转操作以完成身份验证',
        '58106': '请先开通币币杠杆账户',
        '58107': '请先开通交割合约账户',
        '58108': '请先开通期权合约账户',
        '58109': '请先开通永续合约账户',
        '58110': '当前交易产品触发市场风控，平台已暂停相关用户的资金转出功能，请耐心等待',
        '58111': '永续合约正在收取资金费，暂时无法做资金划转，请稍后重试',
        '58112': '资金划转失败，请稍后重试',
        '58114': '转账金额必须大于零（划转接口，金额输入不正确）',
        '58115': '子账户不存在',
        '58116': '转出数量大于最大可转数量',
        '58117': '账户资产异常，请先处理负资产后再划转',
        '58200': '该币种暂不支持从{0}提现至{1}，敬请谅解',
        '58201': '今日提现金额累计超过每日限额',
        '58202': 'NEO最小提现数量为1，且提现数量必须为整数',
        '58203': '请先添加提现地址',
        '58204': '提现冻结',
        '58205': '提现金额大于单笔提现最大金额（单笔提现最大金额提现接口，提现金额输入有误）',
        '58206': '提现金额小于最小提现金额（最小提现金额提现接口，提现金额输入有误）',
        '58207': '提现失败，认证地址错误',
        '58208': '提现失败，邮箱未绑定',
        '58209': '子账户不能充值或提现',
        '58210': '提现手续费大于最大值（提现接口，提现手续费输入有误）',
        '58211': '提现手续费小于最小值（提现接口，手续费输入有误）',
        '58212': '提现手续费应填写为提币数量的{0}%',
        '58213': '提现前请先设置交易密码',
        '58214': '{chainName}维护中，暂停提币',
        '58300': '创建充值地址超过上限',
        '58350': '您的余额不足',
        '58351': 'invoice已经过期',
        '58352': 'invoice无效',
        '58353': '充币数量需要在限额范围内',
        '58354': '单日达到生成invoice100个的上限',
        '58355': '用户没有使用此API接口的权限',
        '58356': '同节点账户不支持闪电网络充币或提币',
        '58357': '币种{0}不允许创建充值地址',
        '59000': '挂单或持仓存在，无法设置',
        '59001': '当前存在借币，暂不可切换',
        '59004': '只支持同一业务线下交易产品ID',
        '59005': '逐仓自主划转保证金模式，初次划入仓位的资产价值需大于10000USDT',
        '59100': '当前存在持仓，请撤销所有挂单后进行杠杆倍数修改',
        '59101': '当前业务存在逐仓挂单，请撤销所有挂单后进行杠杆倍数修改',
        '59102': '杠杆倍数超过最大杠杆倍数，请重新调整杠杆倍数',
        '59103': '杠杆倍数过低，账户中没有足够的可用保证金可以追加，请重新调整杠杆倍数',
        '59104': '杠杆倍数过高，借币仓位已超过该杠杆倍数的最大仓位，请重新调整杠杆倍数',
        '59105': '杠杆倍数设置不能小于{0}，请重新调整杠杆倍数',
        '59106': '您下单后仓位总张数所处档位的最高可用杠杆为{0}，请重新调整',
        '59107': '当前业务存在全仓挂单，请撤销所有挂单后进行杠杆倍数修改',
        '59108': '杠杆倍数过低，账户中保证金不足，请重新调整杠杆倍数',
        '59109': '调整后，账户权益小于所需保证金，请重新调整杠杆倍数',
        '59110': '该{0}对应的产品业务线不支持使用tgtCcy参数',
        '59111': 'PM账户下衍生品全仓不支持杠杆查询',
        '59112': '当前存在逐仓/全仓挂单，请撤销所有逐仓挂单后进行杠杆倍数修改',
        '59200': '账户余额不足',
        '59201': '账户余额是负数',
        '59300': '追加保证金失败，指定仓位不存在',
        '59301': '调整保证金超过当前最大可调整数量',
        '59302': '当前仓位存在平仓挂单，请撤销平仓挂单后进行保证金修改',
        '59303': '可用保证金不足，请尝试增加保证金或减少借币数量',
        '59304': '借币币种权益不足，请至少留有一天的利息',
        '59305': '您当前没有进行尊享借币，无法设置尊享借币优先',
        '59306': '借币数量超过总额度，不可继续借币',
        '59307': '当前用户不满足尊享借币条件',
        '59308': '市场化借币额度不足，VIP还币失败',
        '59309': '还币数量超出已借数量，还币失败',
        '59310': '当前账户不支持尊享借币',
        '59311': '存在尊享借币，无法设置',
        '59312': '{币种}不支持尊享借币',
        '59401': '持仓价值达到持仓限制',
        '59402': '查询条件中的instId的交易产品当前不是可交易状态，请填写单个instid逐个查询状态详情',
        '59500': '仅母账户有操作权限',
        '59501': '每个账户最多可创建50个APIKey',
        '59502': '备注名不可以与当前已创建的APIKey备注名重复',
        '59503': '每个APIKey最多可以绑定20个IP地址',
        '59504': '子账户不支持提币功能',
        '59505': '（区分大小写，不支持空格符号）',
        '59506': 'APIKey不存在',
        '59507': '转出账户和转入账户必须是同一个母账户下的2个不同的子账户',
        '59508': '{0}该子账户被冻结',
        '59601': '子账户名称已存在',
        '59602': '创建的APIkey数量超过上限',
        '59603': '创建子账户超过上限时',
        '59604': '仅母账APIkey有操作此接口的权限',
        '59605': '子账户的APIkey不存在',
        '59606': '删除失败，请将子账户中的余额划转到母账户',
        '59607': '母账交易密码错误',
        '59608': '仅Broker账户有操作此接口的权限',
        '59609': '经纪商已经存在',
        '59610': '经纪商不存在',
        '59611': '经纪商状态是未审核',
        '59612': '时间参数格式转换失败',
    }
else:
    codes = {
        '0': 'Succeeded.',
        '1': 'Operation failed.',
        '2': 'Bulk operation partially succeeded.',
        '50000': 'Body can not be empty.',
        '50001': 'Service temporarily unavailable, please try again later.',
        '50002': 'Json data format error.',
        '50004': 'please check the request result).',
        '50005': 'API is offline or unavailable.',
        '50006': 'Invalid Content_Type, please use "application/json" format.',
        '50007': 'Account blocked.',
        '50008': 'User does not exist.',
        '50009': 'Account is suspended due to ongoing liquidation.',
        '50010': 'User ID can not be empty.',
        '50011': 'Requests too frequent.',
        '50012': 'Account status invalid.',
        '50013': 'System is busy, please try again later.',
        '50014': 'Parameter {0} can not be empty.',
        '50015': 'Either parameter {0} or {1} is required.',
        '50016': 'Parameter {0} does not match parameter {1}.',
        '50017': 'The position is frozen due to ADL. Operation restricted.',
        '50018': 'Currency {0} is frozen due to ADL. Operation restricted.',
        '50019': 'The account is frozen due to ADL. Operation restricted.',
        '50020': 'The position is frozen due to liquidation. Operation restricted.',
        '50021': 'Currency {0} is frozen due to liquidation. Operation restricted.',
        '50022': 'The account is frozen due to liquidation. Operation restricted.',
        '50023': 'Funding fee frozen. Operation restricted.',
        '50024': 'Parameter {0} and {1} can not exist at the same time.',
        '50025': 'Parameter {0} count exceeds the limit {1}.',
        '50026': 'System error.',
        '50027': 'The account is restricted from trading.',
        '50028': 'Unable to take the order, please reach out to support center for details.',
        '50029': 'Please contact customer service for help.',
        '50030': 'No permission to use this API',
        '50031': 'Amount cannot exceed 100',
        '50032': 'This asset is blocked, allow its trading and try again',
        '50033': 'This instrument is blocked, allow its trading and try again',
        '50100': 'API frozen, please contact customer service.',
        '50101': 'Broker id of APIKey does not match current environment.',
        '50102': 'Timestamp request expired.',
        '50103': 'Request header "OK_ACCESS_KEY" can not be empty.',
        '50104': 'Request header "OK_ACCESS_PASSPHRASE" can not be empty.',
        '50105': 'Request header "OK_ACCESS_PASSPHRASE" incorrect.',
        '50106': 'Request header "OK_ACCESS_SIGN" can not be empty.',
        '50107': 'Request header "OK_ACCESS_TIMESTAMP" can not be empty.',
        '50108': 'Exchange ID does not exist.',
        '50109': 'Exchange domain does not exist.',
        '50110': 'Invalid IP.',
        '50111': 'Invalid OK_ACCESS_KEY.',
        '50112': 'Invalid OK_ACCESS_TIMESTAMP.',
        '50113': 'Invalid signature.',
        '50114': 'Invalid authorization.',
        '50115': 'Invalid request method.',
        '51000': 'Parameter {0} error.',
        '51001': 'Instrument ID does not exist.',
        '51002': 'Instrument ID does not match underlying index.',
        '51003': 'Either client order ID or order ID is required.',
        '51004': 'Order amount exceeds current tier limit.',
        '51005': 'Order amount exceeds the limit.',
        '51006': 'Order price out of the limit.',
        '51007': '(showing up when placing an order with less than 1 contract).',
        '51008': 'Order placement failed due to insufficient balance.',
        '51009': 'Order placement function is blocked by the platform.',
        '51010': 'Operation is not supported under the current account mode.',
        '51011': 'Duplicated order ID.',
        '51012': 'Token does not exist.',
        '51014': 'Index does not exist.',
        '51015': 'Instrument ID does not match instrument type.',
        '51016': 'Duplicated client order ID.',
        '51017': 'Borrow amount exceeds the limit.',
        '51018': 'User with option account can not hold net short positions.',
        '51019': 'No net long positions can be held under cross margin mode in options.',
        '51020': 'Order amount should be greater than the min available amount.',
        '51021': 'Contract to be listed.',
        '51022': 'Contract suspended.',
        '51023': 'Position does not exist.',
        '51024': 'Unified accountblocked.',
        '51025': 'Order count exceeds the limit.',
        '51026': 'Instrument type does not match underlying index.',
        '51027': 'Contract expired.',
        '51028': 'Contract under delivery.',
        '51029': 'Contract is being settled.',
        '51030': 'Funding fee is being settled.',
        '51031': 'This order price is not within the closing price range.',
        '51037': 'The current account risk status only supports you to place IOC orders that can reduce the risk of your account.',
        '51038': 'There is already an IOC order under the current risk module that reduces the risk of the account.',
        '51039': 'Leverage cannot be adjusted for the cross positions of Futures and Perpetual swap under the PM account.',
        '51040': 'Cannot adjust margins for long isolated options positions',
        '51041': 'Portfolio margin account only supports net mode.',
        '51044': 'The order type {0}, {1} is not allowed to set stop loss and take profit',
        '51046': 'The take profit trigger price should be higher than the order price',
        '51047': 'The stop loss trigger price should be lower than the order price',
        '51048': 'The take profit trigger price should be lower than the order price',
        '51049': 'The stop loss trigger price should be higher than the order price',
        '51050': 'The take profit trigger price should be higher than the best ask price',
        '51051': 'The stop loss trigger price should be lower than the best ask price',
        '51052': 'The take profit trigger price should be lower than the best bid price',
        '51053': 'The stop loss trigger price should be higher than the best bid price',
        '51100': 'Trading amount does not meet the min tradable amount.',
        '51101': 'per transaction.',
        '51102': 'Entered amount exceeds the max pending count.',
        '51103': 'Entered amount exceeds the max pending order count of the underlying asset.',
        '51104': 'of the underlying asset.',
        '51105': 'Entered amount exceeds the max order amount (Cont) of the contract.',
        '51106': 'underlying asset.',
        '51107': 'Entered amount exceeds the max holding amount (Cont).',
        '51108': 'Positions exceed the limit for closing out with the market price.',
        '51109': 'No available offer.',
        '51110': 'You can only place a limit order after Call Auction has started.',
        '51111': 'Maximum {0} orders can be placed in bulk.',
        '51112': 'Close order size exceeds your available size.',
        '51113': 'Market-price liquidation requests too frequent.',
        '51115': 'Cancel all pending close-orders before liquidation.',
        '51116': 'Order price or trigger price exceeds {0}.',
        '51117': 'Pending close-orders count exceeds limit.',
        '51118': 'Total amount should exceed the min amount per order.',
        '51120': 'Order quantity is less than {0}, please try again.',
        '51121': 'Order count should be the integer multiples of the lot size.',
        '51122': 'Order price should be higher than the min price {0}.',
        '51124': 'You can only place limit orders during call auction.',
        '51125': 'Please cancel all reduce + reverse position pending orders and continue.',
        '51126': 'Please cancel all reduce only pending orders and continue.',
        '51127': 'Available balance is 0.',
        '51128': 'Multi-currency margin account can not do cross-margin trading.',
        '51129': 'and no further buying is allowed.',
        '51130': 'Fixed margin currency error.',
        '51131': 'Insufficient balance.',
        '51132': 'Your position amount is negative and less than the minimum trading amount.',
        '51133': 'multi-currency margin account.',
        '51134': 'Closing failed. Please check your holdings and pending orders.',
        '51135': 'Your closing price has triggered the limit price, and the max buy price is {0}.',
        '51136': 'Your closing price has triggered the limit price, and the min sell price is {0}.',
        '51137': 'Your opening price has triggered the limit price, and the max buy price is {0}.',
        '51138': 'Your opening price has triggered the limit price, and the min sell price is {0}.',
        '51139': 'Reduce-only feature is unavailable for the spot transactions by simple account.',
        '51145': 'When users transfer the margin by themselves in isolated mode, it’s not supported to place orders in advance',
        '51147': 'The total value of assets in your Trading account needs to be greater than 50,000 USD to trade options',
        '51148': 'ReduceOnly cannot increase the position quantity.',
        '51201': 'Value of per market order cannot exceed 1,000,000 USDT.',
        '51202': 'Market - order amount exceeds the max amount.',
        '51203': 'Order amount exceeds the limit {0}.',
        '51204': 'The price for the limit order can not be empty.',
        '51205': 'Reduce-Only is not available.',
        '51250': 'Algo order price is out of the available range.',
        '51251': 'Algo order type error (when user place an iceberg order).',
        '51252': 'Algo order price is out of the available range.',
        '51253': 'Average amount exceeds the limit of per iceberg order.',
        '51254': 'Iceberg average amount error (when user place an iceberg order).',
        '51255': 'Limit of per iceberg order: Total amount/1000 < x <= Total amount.',
        '51256': 'Iceberg order price variance error.',
        '51257': 'Trail order callback rate error.',
        '51258': 'should be higher than the last transaction price.',
        '51259': 'should be lower than the last transaction price.',
        '51260': 'Maximum {0} pending trail - orders can be held at the same time.',
        '51261': 'Each user can hold up to {0} pending stop - orders at the same time.',
        '51262': 'Maximum {0} pending iceberg orders can be held at the same time.',
        '51263': 'Maximum {0} pending time-weighted orders can be held at the same time.',
        '51264': 'Average amount exceeds the limit of per time-weighted order.',
        '51265': 'Time-weighted order limit error.',
        '51267': 'Time-weighted order strategy initiative rate error.',
        '51268': 'Time-weighted order strategy initiative range error.',
        '51269': 'Time-weighted order interval error, the interval should be {0}<= x<={1}.',
        '51270': 'The limit of time-weighted order price variance is 0 < x <= 1%.',
        '51271': 'Sweep ratio should be 0 < x <= 100%.',
        '51272': 'Price variance should be 0 < x <= 1%.',
        '51273': 'Total amount should be more than {0}.',
        '51274': 'Total quantity of time-weighted order must be larger than single order limit.',
        '51275': 'The amount of single stop-market order can not exceed the upper limit.',
        '51276': 'Stop - Market orders cannot specify a price.',
        '51277': 'TP trigger price can not be higher than the last price.',
        '51278': 'SL trigger price can not be lower than the last price.',
        '51279': 'TP trigger price can not be lower than the last price.',
        '51280': 'SL trigger price can not be higher than the last price.',
        '51281': 'trigger not support the tgtCcy parameter.',
        '51282': 'The range of Price variance is {0}~{1}',
        '51283': 'The range of Time interval is {0}~{1}',
        '51284': 'The range of Average amount is {0}~{1}',
        '51285': 'The range of Total amount is {0}~{1}',
        '51286': 'The total amount should not be less than {0}',
        '51287': 'Contract not supported',
        '51288': 'We are stopping the Bot. Please do not click it multiple times',
        '51289': 'Bot configuration does not exist. Please try again later',
        '51290': 'The Bot engine is being upgraded. Please try again later',
        '51291': 'This Bot does not exist or has been stopped',
        '51292': 'This Bot type does not exist',
        '51293': 'This Bot does not exist',
        '51294': 'This Bot cannot be created temporarily. Please try again later',
        '51295': 'Portfolio margin account does not support ordType {0} in Trading bot mode',
        '51298': 'Trigger orders are not available in the net mode of futures and perpetual swaps',
        '51299': 'Order did not go through. You can hold maximum {0} orders of this type',
        '51300': 'TP trigger price can not be higher than the mark price',
        '51302': 'SL trigger price can not be lower than the mark price',
        '51303': 'TP trigger price can not be lower than the mark price',
        '51304': 'SL trigger price can not be higher than the mark price',
        '51305': 'TP trigger price can not be higher than the index price',
        '51306': 'SL trigger price can not be lower than the index price',
        '51307': 'TP trigger price can not be lower than the index price',
        '51308': 'SL trigger price can not be higher than the index price',
        '51309': 'Cannot create trading bot during call auction',
        '51310': 'When users transfer the margin by themselves in isolated mode, strategic orders with ordType iceberg and twap will not be supported',
        '51311': 'Failed to place trailing stop order. Callback rate should be within {0}<x<={1}',
        '51312': 'Failed to place trailing stop order. Order amount should be within {0}<x<={1}',
        '51313': 'Manual transfer in isolated mode does not support bot trading',
        '51400': 'Cancellation failed as the order does not exist.',
        '51401': 'Cancellation failed as the order is already canceled.',
        '51402': 'Cancellation failed as the order is already completed.',
        '51403': 'Cancellation failed as the order type does not support cancellation.',
        '51404': 'Order cancellation unavailable during the second phase of call auction.',
        '51405': 'Cancellation failed as you do not have any pending orders.',
        '51406': 'Canceled - order count exceeds the limit {0}.',
        '51407': 'Either order ID or client order ID is required.',
        '51408': 'Pair ID or name does not match the order info.',
        '51409': 'Either pair ID or pair name ID is required.',
        '51410': 'Cancellation failed as the order is already under cancelling status.',
        '51500': 'Either order price or amount is required.',
        '51501': 'Maximum {0} orders can be modified.',
        '51502': 'Order modification failed for insufficient margin.',
        '51503': 'Order modification failed as the order does not exist.',
        '51506': 'Order modification unavailable for the order type.',
        '51508': 'Orders are not allowed to be modified during the call auction.',
        '51509': 'Modification failed as the order has been canceled.',
        '51510': 'Modification failed as the order has been completed.',
        '51511': 'Modification failed as the order price did not meet the requirement for Post Only.',
        '51512': 'Failed to amend bulk orders. You cannot add duplicate batch orders in your Portfolio margin account.',
        '51513': 'Unable to verify, try again later',
        '51600': 'Status not found.',
        '51601': 'Order status and order ID cannot exist at the same time.',
        '51602': 'Either order status or order ID is required.',
        '51603': 'Order does not exist.',
        '52000': 'No updates.',
        '54000': 'Margin transactions unavailable.',
        '54001': 'Only Multi-currency margin account can be set to borrow coins automatically.',
        '55000': 'Cannot be transferred out within 30 minutes after delivery.',
        '58000': 'Account type {0} does not supported when getting the sub-account balance.',
        '58001': 'Incorrect trade password.',
        '58002': 'Please activate Savings Account first.',
        '58003': 'Currency type is not supported by Savings Account.',
        '58004': 'either end of the account does not authorize the transfer).',
        '58005': 'The purchase/redeemed amount must be no greater than {0}.',
        '58006': 'Service unavailable for token {0}.',
        '58007': 'Abnormal Assets interface. Please try again later.',
        '58100': 'the fund transfer-out function with related users. Please wait patiently.',
        '58101': 'does not authorize the transfer).',
        '58102': 'Too frequent transfer (transfer too frequently).',
        '58103': 'Parent account user id does not match sub-account user id.',
        '58104': 'fund transfers. Please contact customer support to remove the restriction.',
        '58105': 'identity verification.',
        '58106': 'Please enable the account for spot contract.',
        '58107': 'Please enable the account for futures contract.',
        '58108': 'Please enable the account for option contract.',
        '58109': 'Please enable the account for swap contract.',
        '58110': 'transfer function of it. Please wait patiently.',
        '58111': 'fee. Please try again later.',
        '58112': 'Your fund transfer failed. Please try again later.',
        '58114': 'Transfer amount must be more than 0.',
        '58115': 'Sub-account does not exist.',
        '58116': 'Transfer amount exceeds the limit.',
        '58117': 'Account assets are abnormal, please deal with negative assets before transferring.',
        '58200': 'Withdrawal from {0} to {1} is unavailable for this currency.',
        '58201': 'Withdrawal amount exceeds the daily limit.',
        '58202': 'The minimum withdrawal amount for NEO is 1, and the amount must be an integer.',
        '58203': 'Please add a withdrawal address.',
        '58204': 'Withdrawal suspended.',
        '58205': 'Withdrawal amount exceeds the upper limit.',
        '58206': 'Withdrawal amount is lower than the lower limit.',
        '58207': 'Withdrawal failed due to address error.',
        '58208': 'Withdrawal failed. Please link your email.',
        '58209': 'Sub-accounts cannot be deposits or withdrawals',
        '58210': 'Withdrawal fee exceeds the upper limit.',
        '58211': 'Withdrawal fee is lower than the lower limit (withdrawal endpoint: incorrect fee).',
        '58212': 'Withdrawal fee should be {0}% of the withdrawal amount.',
        '58213': 'Please set trading password before withdrawal.',
        '58214': 'Withdrawals suspended due to {chainName} maintenance',
        '58300': 'Deposit-address count exceeds the limit.',
        '58350': 'Insufficient balance.',
        '58351': 'Invoice expired.',
        '58352': 'Invalid invoice.',
        '58353': 'Deposit amount must be within limits.',
        '58354': 'You have reached the limit of 100 invoices per day.',
        '58355': 'Permission denied. Please contact your account manager.',
        '58356': 'The accounts of the same node do not support the Lightning network deposit or withdrawal.',
        '58357': '{0} is not allowed to create a deposit address',
        '59000': 'Your settings failed as you have positions or open orders.',
        '59001': 'Switching unavailable as you have borrowings.',
        '59004': 'Only IDs with the same instrument type are supported',
        '59005': 'When users transfer the margin by themselves in isolated mode, the value of the asset allocated to the position for the first time must be greater than 10,000 USDT',
        '59100': 'the leverage.',
        '59101': 'pending orders and adjust the leverage.',
        '59102': 'Leverage exceeds the maximum leverage. Please adjust the leverage.',
        '59103': 'adjust the leverage.',
        '59104': 'maximum position of this leverage. Please adjust the leverage.',
        '59105': 'Leverage can not be less than {0}. Please adjust the leverage.',
        '59106': 'Please adjust your margin and place a new order.',
        '59107': 'after canceling all pending orders.',
        '59108': 'Low leverage and insufficient margin, please adjust the leverage.',
        '59109': 'Please adjust the leverage .',
        '59110': 'The instrument type corresponding to this {0} does not support the tgtCcy parameter.',
        '59111': 'You cannot query the leverage of cross derivatives positions under a PM account.',
        '59112': 'You have isolated/cross pending orders. Please cancel them before adjusting your leverage',
        '59200': 'Insufficient account balance.',
        '59201': 'Negative account balance.',
        '59300': 'Margin call failed. Position does not exist.',
        '59301': 'Margin adjustment failed for exceeding the max limit.',
        '59302': 'You have pending close orders, please modify the margin after canceling the orders.',
        '59303': 'Insufficient available margin, add margin or reduce the borrowing amount',
        '59304': 'Insufficient equity for borrowing, keep enough funds to pay interest for at least one day',
        '59305': 'Use VIP loan first to set the VIP loan priority',
        '59306': 'Your borrowing amount exceeds the max limit',
        '59307': 'You are not eligible for VIP loans',
        '59308': 'Unable to repay VIP loan due to insufficient borrow limit',
        '59309': 'Unable to repay an amount that exceeds the borrowed amount',
        '59310': 'Your account does not support VIP loan',
        '59311': 'Unable to set up as there is VIP loan',
        '59312': '{currency} does not support VIP loans',
        '59401': 'Holdings already reached the limit.',
        '59402': 'None of the passed instId is in live state, please check them separately.',
        '59500': 'Only the APIKey of the main account has permission.',
        '59501': 'Only 50 APIKeys can be created per account.',
        '59502': 'Note name cannot be duplicate with the currently created APIKey note name.',
        '59503': 'Each APIKey can bind up to 20 IP addresses.',
        '59504': 'The sub account does not support the withdrawal function.',
        '59505': 'The passphrase format is incorrect.',
        '59506': 'APIKey does not exist.',
        '59507': 'under the same parent account.',
        '59508': 'The sub account of {0} is suspended.',
        '59601': 'This sub-account name already exists, try another name',
        '59602': 'Number of API keys exceeds the limit',
        '59603': 'Number of sub accounts exceeds the limit',
        '59604': 'Only the main account APIkey can access this API',
        '59605': 'This API key does not exist in your sub-account, try another API key',
        '59606': 'Transfer funds to your main account before deleting your sub-account',
        '59607': 'Incorrect trades password',
        '59608': 'Only the Broker account has permission to operate this API',
        '59609': 'Broker already exists',
        '59610': 'Broker does not exist',
        '59611': 'Broker unverified',
        '59612': 'Cannot convert time format',
    }
